spring.application.name: elms

jwt.secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

spring:
  datasource:
    url: jdbc:h2:file./data/leaveManagementApplication12
    driver-class-name: org.h2.Driver
    username: sa
    password:


  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false


logging:
  file:
    name: logs/app.log
  level:
    root: OFF
    com.infinite.elms: WARN
    com.infinite.elms.controller: INFO
